---
- name: install php
  yum: name={{ item }} state=latest
  with_items:
    - php 
    - php-fpm 
    - php-mysql
- name: start php-fpm and boot enabled
  service: name=php-fpm state=started enabled=yes
