---
- name: get jenkins repo 
  command: wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo
- name: install jenkins 
  command: rpm --import http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key
- name: install Jenkins by yum 
  yum: name=jenkins state=latest
- name: install Java 
  yum: name=java-1.7.0-openjdk state=latest 
- name: start jenkins
  service: name=jenkins state=started enabled=yes
   
       
