---
- name: create sshkey and upload to digitalocean 
  script: create_sshkey.sh
- name: fetch pub key from destination
  fetch: src=/var/lib/jenkins/.ssh/id_rsa.pub dest=/tmp/ flat=yes
- name: upload sshkey to digitalocean
  delegate_to: 127.0.0.1
  script: doman.pl --create_sshkey -sshkey_name jenkins -pub_sshkey /tmp/id_rsa.pub
   
       
