---
#- name: install epel 
#  shell: rpm -ivh http://ftp.jaist.ac.jp/pub/Linux/Fedora/epel/6/i386/epel-release-6-8.noarch.rpm 
- name: install docker-io 
  yum: name=docker-io state=latest
- name: start docker-io 
  service: name=docker state=started enabled=yes
   
       
