---
# file: stage.yml
- hosts: all
  remote_user: root
  roles:
    - epel-6.8
    - ansible
    - openssl-1.0.1f
    #- perl5.18.2_system
    - packer-0.5.2
    #- docker
    - jenkins 
    - mosh
    - add_user_to_docker_grp 
    #- digitalocean-jenkins-sshkey
    - serverspec 
    #- python
    #- digitalocean

