---
- name: install openssl-devel
  yum: name=openssl-devel state=latest
- name: Install openssl 
  get_url: url=http://www.openssl.org/source/openssl-1.0.1f.tar.gz dest=/tmp
- script: install_openssl.sh 
- name: install perl with perlenv 
  remote_user: kamesho
  script: perlenv.sh 
- name: copy cpanfile to /tmp/
  remote_user: kamesho
  copy: src=cpanfile dest=/tmp/cpanfile
- name: install modules
  remote_user: kamesho
  script: install_with_cpanm.sh 
       

